# Generated by Django 4.2.7 on 2025-11-24 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=255)),
                ('stock', models.IntegerField(default=1)),
                ('measure', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('quality', models.IntegerField(choices=[(1, 'Freshly Harvested'), (2, 'New Stocks'), (3, 'Well Preserved')], default=3)),
                ('type', models.IntegerField(choices=[(1, 'Organic'), (2, 'Inorganic'), (3, 'Local'), (4, 'Foreign')], default=3)),
                ('image', models.ImageField(default='LA.png', upload_to='productImage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
